// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GestureSystemUnparentMovableObjectHandler {
        
        public MovableObject Group;
        
        private abgabe.UnparentMovableObject _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool ActionNode72_value = default( System.Boolean );
        
        private object NullNode57;
        
        private float ActionNode63_x = default( System.Single );
        
        private float ActionNode63_y = default( System.Single );
        
        private float ActionNode63_z = default( System.Single );
        
        private float FloatNode64 = 0.35F;
        
        private UnityEngine.Vector3 ActionNode63_Result = default( UnityEngine.Vector3 );
        
        private uFrame.ECS.Entity ActionNode68_entity = default( uFrame.ECS.Entity );
        
        private int ActionNode89_in = default( System.Int32 );
        
        private int IntNode88 = 0;
        
        private float ActionNode89_Result = default( System.Single );
        
        private float ActionNode87_x = default( System.Single );
        
        private float ActionNode87_y = default( System.Single );
        
        private int ActionNode90_in = default( System.Int32 );
        
        private float ActionNode90_Result = default( System.Single );
        
        private float ActionNode87_z = default( System.Single );
        
        private UnityEngine.Vector3 ActionNode87_Result = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode68_rotation = default( UnityEngine.Vector3 );
        
        private bool BoolNode71 = true;
        
        public abgabe.UnparentMovableObject Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode72_value = Group.isPlaced;
            // ActionNode
            while (this.DebugInfo("c6860e7b-35d9-4d2e-ae20-8161109d226d","5bb81a4a-b267-4d9a-8a48-2a34f07081dc", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.IsTrue
            uFrame.Actions.Comparisons.IsTrue(ActionNode72_value, ()=> { System.StartCoroutine(ActionNode72_yes()); }, ()=> { System.StartCoroutine(ActionNode72_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode72_yes() {
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode72_no() {
            // SetVariableNode
            while (this.DebugInfo("5bb81a4a-b267-4d9a-8a48-2a34f07081dc","e8db2df5-4b74-4d34-bee2-9720e9cec588", this) == 1) yield return null;
            Group.gameObject.transform.parent = (UnityEngine.Transform)NullNode57;
            ActionNode63_x = Group.gameObject.transform.position.x;
            ActionNode63_y = Group.gameObject.transform.position.y;
            ActionNode63_z = FloatNode64;
            // ActionNode
            while (this.DebugInfo("e8db2df5-4b74-4d34-bee2-9720e9cec588","7b087719-0392-408f-88c7-4f6f8281fa8c", this) == 1) yield return null;
            // Visit uFrame.Actions.Vector3Library.Create
            ActionNode63_Result = uFrame.Actions.Vector3Library.Create(ActionNode63_x, ActionNode63_y, ActionNode63_z);
            // SetVariableNode
            while (this.DebugInfo("7b087719-0392-408f-88c7-4f6f8281fa8c","d90d1ba3-2a6b-480d-9ec4-e988c618c308", this) == 1) yield return null;
            Group.gameObject.transform.position = (UnityEngine.Vector3)ActionNode63_Result;
            ActionNode68_entity = Group._Entity;
            ActionNode89_in = IntNode88;
            // ActionNode
            while (this.DebugInfo("d90d1ba3-2a6b-480d-9ec4-e988c618c308","77d285b9-224b-402c-b153-a91366614213", this) == 1) yield return null;
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode89_Result = uFrame.Actions.Converter.IntToFloat(ActionNode89_in);
            ActionNode87_x = ActionNode89_Result;
            ActionNode87_y = ActionNode89_Result;
            ActionNode90_in = Group.rotation;
            // ActionNode
            while (this.DebugInfo("77d285b9-224b-402c-b153-a91366614213","5f0400cc-76eb-4ea6-a6b6-939b8467bdc4", this) == 1) yield return null;
            // Visit uFrame.Actions.Converter.IntToFloat
            ActionNode90_Result = uFrame.Actions.Converter.IntToFloat(ActionNode90_in);
            ActionNode87_z = ActionNode90_Result;
            // ActionNode
            while (this.DebugInfo("5f0400cc-76eb-4ea6-a6b6-939b8467bdc4","8e0a4c3f-9d99-4f4a-b199-30466263dabc", this) == 1) yield return null;
            // Visit uFrame.Actions.Vector3Library.Create
            ActionNode87_Result = uFrame.Actions.Vector3Library.Create(ActionNode87_x, ActionNode87_y, ActionNode87_z);
            ActionNode68_rotation = ActionNode87_Result;
            // ActionNode
            while (this.DebugInfo("8e0a4c3f-9d99-4f4a-b199-30466263dabc","740e42b9-8f47-4950-883c-9e539088c4fb", this) == 1) yield return null;
            // Visit uFrame.Actions.EntityTransform.SetRotation
            uFrame.Actions.EntityTransform.SetRotation(ActionNode68_entity, ActionNode68_rotation);
            // SetVariableNode
            while (this.DebugInfo("740e42b9-8f47-4950-883c-9e539088c4fb","5d36b5f4-52a1-49d8-96a8-e3b96a89f30e", this) == 1) yield return null;
            Group.isPlaced = (System.Boolean)BoolNode71;
            yield break;
        }
    }
}
