// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GestureSystemRightPinchDetectedHandler {
        
        private abgabe.RightPinchDetected _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private abgabe.HideMenuEvent PublishEventNode37_Result = default( abgabe.HideMenuEvent );
        
        public abgabe.RightPinchDetected Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // PublishEventNode
            while (this.DebugInfo("b873baca-6656-4f1a-b6a0-d2c3aa5cc5b3","a0c6cf41-a912-4eec-9ff2-b4260ec9d793", this) == 1) yield return null;
            var PublishEventNode37_Event = new HideMenuEvent();
            System.Publish(PublishEventNode37_Event);
            PublishEventNode37_Result = PublishEventNode37_Event;
            yield break;
        }
    }
}
