// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class InitSystemGameReadyHandler {
        
        public SubMenuComponent Group;
        
        private uFrame.Kernel.GameReadyEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode1_obj = default( UnityEngine.GameObject );
        
        private bool ActionNode1_state = default( System.Boolean );
        
        private bool BoolNode2 = false;
        
        public uFrame.Kernel.GameReadyEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode1_obj = Group.gameObject;
            ActionNode1_state = BoolNode2;
            // ActionNode
            while (this.DebugInfo("f5948aeb-f349-443f-ae1e-80e6721713d1","ae44748e-b158-46a3-99d1-5b7a0b6fdc5f", this) == 1) yield return null;
            // Visit GameObjectUtils.setActive
            GameObjectUtils.setActive(ActionNode1_obj, ActionNode1_state);
            yield break;
        }
    }
}
