// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class InitSystemGameReady2Handler {
        
        public MenuComponent Group;
        
        private uFrame.Kernel.GameReadyEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode4_obj = default( UnityEngine.GameObject );
        
        private bool ActionNode4_state = default( System.Boolean );
        
        private bool BoolNode5 = false;
        
        public uFrame.Kernel.GameReadyEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode4_obj = Group.gameObject;
            ActionNode4_state = BoolNode5;
            // ActionNode
            while (this.DebugInfo("6623a4ff-3254-4f72-8959-e1ad3aeb6a1a","d5e92b94-a972-4fd7-8581-56f4ba694c82", this) == 1) yield return null;
            // Visit GameObjectUtils.setActive
            GameObjectUtils.setActive(ActionNode4_obj, ActionNode4_state);
            yield break;
        }
    }
}
