// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuSystemMenuSelectEventHandler {
        
        public SubMenuComponent Group;
        
        private abgabe.MenuSelectEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private object ActionNode11_a = default( System.Object );
        
        private object ActionNode11_b = default( System.Object );
        
        private bool ActionNode11_Result = default( System.Boolean );
        
        private UnityEngine.GameObject ActionNode12_obj = default( UnityEngine.GameObject );
        
        private bool ActionNode12_state = default( System.Boolean );
        
        private bool BoolNode13 = true;
        
        private UnityEngine.GameObject ActionNode14_obj = default( UnityEngine.GameObject );
        
        private bool ActionNode14_state = default( System.Boolean );
        
        private bool BoolNode15 = false;
        
        public abgabe.MenuSelectEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode11_a = Group.index;
            ActionNode11_b = Event.index;
            // ActionNode
            while (this.DebugInfo("7bb5713f-24e4-458d-8eee-c7d5dbc970bb","075d4b04-c334-47c9-babd-8d3399520fdd", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.AreEqual
            ActionNode11_Result = uFrame.Actions.Comparisons.AreEqual(ActionNode11_a, ActionNode11_b, ()=> { System.StartCoroutine(ActionNode11_yes()); }, ()=> { System.StartCoroutine(ActionNode11_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode11_yes() {
            ActionNode12_obj = Group.gameObject;
            ActionNode12_state = BoolNode13;
            // ActionNode
            while (this.DebugInfo("075d4b04-c334-47c9-babd-8d3399520fdd","08579390-e659-4eaa-90ea-70fb835e82bb", this) == 1) yield return null;
            // Visit GameObjectUtils.setActive
            GameObjectUtils.setActive(ActionNode12_obj, ActionNode12_state);
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode11_no() {
            ActionNode14_obj = Group.gameObject;
            ActionNode14_state = BoolNode15;
            // ActionNode
            while (this.DebugInfo("08579390-e659-4eaa-90ea-70fb835e82bb","2839e6dd-e2ec-4d7a-9364-bbc4a2ca0cc0", this) == 1) yield return null;
            // Visit GameObjectUtils.setActive
            GameObjectUtils.setActive(ActionNode14_obj, ActionNode14_state);
            yield break;
        }
    }
}
