// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuSystemOnTriggerEnterHandler {
        
        public MenuItemComponent Collider;
        
        public MenuSelectionComponent Source;
        
        private uFrame.ECS.OnTriggerEnterDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private abgabe.MenuSelectEvent PublishEventNode7_Result = default( abgabe.MenuSelectEvent );
        
        public uFrame.ECS.OnTriggerEnterDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // PublishEventNode
            while (this.DebugInfo("d5e92b94-a972-4fd7-8581-56f4ba694c82","1f9dbb58-bffb-450a-8889-ee2a86902655", this) == 1) yield return null;
            var PublishEventNode7_Event = new MenuSelectEvent();
            PublishEventNode7_Event.index = Collider.index;
            System.Publish(PublishEventNode7_Event);
            PublishEventNode7_Result = PublishEventNode7_Event;
            yield break;
        }
    }
}
