// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuSystemHideMenuEventHandler {
        
        public MenuComponent Group;
        
        private abgabe.HideMenuEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode39_obj = default( UnityEngine.GameObject );
        
        private bool ActionNode39_state = default( System.Boolean );
        
        private bool BoolNode40 = false;
        
        public abgabe.HideMenuEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode39_obj = Group.gameObject;
            ActionNode39_state = BoolNode40;
            // ActionNode
            while (this.DebugInfo("d0332702-b94e-4430-b85e-7d0060a07905","d7318fd2-3da5-4dd8-bfa4-db92d34c7bce", this) == 1) yield return null;
            // Visit GameObjectUtils.setActive
            GameObjectUtils.setActive(ActionNode39_obj, ActionNode39_state);
            yield break;
        }
    }
}
