// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuSystemSubMenuSelectEventHandler {
        
        private abgabe.SubMenuSelectEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode46_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.Vector3 ActionNode46_position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode46_rotation = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 Vector3Node47 = new UnityEngine.Vector3(0f,0f,0f);
        
        private UnityEngine.GameObject ActionNode46_Result = default( UnityEngine.GameObject );
        
        private object ActionNode50_message = default( System.Object );
        
        public abgabe.SubMenuSelectEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode46_gameObject = Event.instantiate;
            ActionNode46_position = Event.msc.transform.position;
            ActionNode46_rotation = Vector3Node47;
            // ActionNode
            while (this.DebugInfo("a0c6cf41-a912-4eec-9ff2-b4260ec9d793","7a220324-ab6a-4f4d-9c68-4419c3ba8e51", this) == 1) yield return null;
            // Visit uFrame.Actions.GameObjects.Instantiate
            ActionNode46_Result = uFrame.Actions.GameObjects.Instantiate(ActionNode46_gameObject, ActionNode46_position, ActionNode46_rotation);
            // SetVariableNode
            while (this.DebugInfo("7a220324-ab6a-4f4d-9c68-4419c3ba8e51","b3c34231-140b-4b70-9744-fc05909d3e4c", this) == 1) yield return null;
            ActionNode46_Result.transform.parent = (UnityEngine.Transform)Event.msc.transform;
            ActionNode50_message = ActionNode46_Result.transform.parent;
            // ActionNode
            while (this.DebugInfo("b3c34231-140b-4b70-9744-fc05909d3e4c","f5948aeb-f349-443f-ae1e-80e6721713d1", this) == 1) yield return null;
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode50_message);
            yield break;
        }
    }
}
