// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuSystemOnTriggerEnter2Handler {
        
        public SubMenuItemComponent Collider;
        
        public MenuSelectionComponent Source;
        
        private uFrame.ECS.OnTriggerEnterDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private abgabe.SubMenuSelectEvent PublishEventNode9_Result = default( abgabe.SubMenuSelectEvent );
        
        public uFrame.ECS.OnTriggerEnterDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // PublishEventNode
            while (this.DebugInfo("1f9dbb58-bffb-450a-8889-ee2a86902655","7bb5713f-24e4-458d-8eee-c7d5dbc970bb", this) == 1) yield return null;
            var PublishEventNode9_Event = new SubMenuSelectEvent();
            PublishEventNode9_Event.msc = Source.gameObject;
            PublishEventNode9_Event.index = Collider.index;
            System.Publish(PublishEventNode9_Event);
            PublishEventNode9_Result = PublishEventNode9_Event;
            yield break;
        }
    }
}
