// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuSystemOnTriggerEnter2Handler {
        
        public SubMenuItemComponent Collider;
        
        public MenuSelectionComponent Source;
        
        private uFrame.ECS.OnTriggerEnterDispatcher _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private abgabe.SubMenuSelectEvent PublishEventNode44_Result = default( abgabe.SubMenuSelectEvent );
        
        private abgabe.HideMenuEvent PublishEventNode49_Result = default( abgabe.HideMenuEvent );
        
        public uFrame.ECS.OnTriggerEnterDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // PublishEventNode
            while (this.DebugInfo("2839e6dd-e2ec-4d7a-9364-bbc4a2ca0cc0","bc9b50b4-f7a4-4342-bf34-f93d25bffdc1", this) == 1) yield return null;
            var PublishEventNode44_Event = new SubMenuSelectEvent();
            PublishEventNode44_Event.msc = Source.gameObject;
            PublishEventNode44_Event.instantiate = Collider.instantiate;
            System.Publish(PublishEventNode44_Event);
            PublishEventNode44_Result = PublishEventNode44_Event;
            // PublishEventNode
            while (this.DebugInfo("bc9b50b4-f7a4-4342-bf34-f93d25bffdc1","9b7433f5-a4f4-48e1-924a-7034e2c31302", this) == 1) yield return null;
            var PublishEventNode49_Event = new HideMenuEvent();
            System.Publish(PublishEventNode49_Event);
            PublishEventNode49_Result = PublishEventNode49_Event;
            yield break;
        }
    }
}
