// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ModifyObjectSystemDeleteObjectEventHandler {
        
        public MovableObject Group;
        
        private abgabe.DeleteObjectEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool ActionNode84_value = default( System.Boolean );
        
        private UnityEngine.GameObject ActionNode85_gameObject = default( UnityEngine.GameObject );
        
        private float ActionNode85_time = default( System.Single );
        
        private float FloatNode86 = 0F;
        
        public abgabe.DeleteObjectEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode84_value = Group.isPlaced;
            // ActionNode
            while (this.DebugInfo("914ef933-cb2a-46d4-9ef7-6298dc7d7943","c4607311-26af-45d1-aaeb-384cc8a95196", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.IsTrue
            uFrame.Actions.Comparisons.IsTrue(ActionNode84_value, ()=> { System.StartCoroutine(ActionNode84_yes()); }, ()=> { System.StartCoroutine(ActionNode84_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode84_yes() {
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode84_no() {
            ActionNode85_gameObject = Group.gameObject;
            ActionNode85_time = FloatNode86;
            // ActionNode
            while (this.DebugInfo("c4607311-26af-45d1-aaeb-384cc8a95196","b873baca-6656-4f1a-b6a0-d2c3aa5cc5b3", this) == 1) yield return null;
            // Visit uFrame.Actions.DestroyLibrary.DestroyGameObject
            uFrame.Actions.DestroyLibrary.DestroyGameObject(ActionNode85_gameObject, ActionNode85_time);
            yield break;
        }
    }
}
