// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ModifyObjectSystemRotateObjectEventHandler {
        
        public MovableObject Group;
        
        private abgabe.RotateObjectEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool ActionNode96_value = default( System.Boolean );
        
        private int ActionNode98_a = default( System.Int32 );
        
        private int ActionNode98_b = default( System.Int32 );
        
        private int IntNode99 = 25;
        
        private int ActionNode98_Result = default( System.Int32 );
        
        public abgabe.RotateObjectEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode96_value = Group.isPlaced;
            // ActionNode
            while (this.DebugInfo("d5e92b94-a972-4fd7-8581-56f4ba694c82","def58250-ff60-4325-bca7-d19a9cd7cdfd", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.IsTrue
            uFrame.Actions.Comparisons.IsTrue(ActionNode96_value, ()=> { System.StartCoroutine(ActionNode96_yes()); }, ()=> { System.StartCoroutine(ActionNode96_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode96_yes() {
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode96_no() {
            ActionNode98_a = Group.rotation;
            ActionNode98_b = IntNode99;
            // ActionNode
            while (this.DebugInfo("def58250-ff60-4325-bca7-d19a9cd7cdfd","f54b2c95-a23b-4706-87be-12d7f17d6ff3", this) == 1) yield return null;
            // Visit uFrame.Actions.IntLibrary.Add
            ActionNode98_Result = uFrame.Actions.IntLibrary.Add(ActionNode98_a, ActionNode98_b);
            // SetVariableNode
            while (this.DebugInfo("f54b2c95-a23b-4706-87be-12d7f17d6ff3","13b421ac-b8bb-421b-8bbc-7288bbae28dd", this) == 1) yield return null;
            Group.rotation = (System.Int32)ActionNode98_Result;
            yield break;
        }
    }
}
