// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class UpdateSystemUpdateHandler {
        
        private uFrame.ECS.ISystemUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        public uFrame.ECS.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // ActionNode
            while (this.DebugInfo("d7318fd2-3da5-4dd8-bfa4-db92d34c7bce","6623a4ff-3254-4f72-8959-e1ad3aeb6a1a", this) == 1) yield return null;
            // Visit ComplexGestureUtils.update
            ComplexGestureUtils.update();
            // ActionNode
            while (this.DebugInfo("6623a4ff-3254-4f72-8959-e1ad3aeb6a1a","71e05e61-f2bd-4fa3-a30e-1db405dff358", this) == 1) yield return null;
            // Visit GestureUtils.update
            GestureUtils.update();
            yield break;
        }
    }
}
