// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using abgabe;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class InitSystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<SubMenuComponent> _SubMenuComponentManager;
        
        private IEcsComponentManagerOf<MenuItemComponent> _MenuItemComponentManager;
        
        private IEcsComponentManagerOf<MenuSelectionComponent> _MenuSelectionComponentManager;
        
        private IEcsComponentManagerOf<MenuComponent> _MenuComponentManager;
        
        private IEcsComponentManagerOf<SubMenuItemComponent> _SubMenuItemComponentManager;
        
        private IEcsComponentManagerOf<RightHandComponent> _RightHandComponentManager;
        
        private IEcsComponentManagerOf<LeftHandComponent> _LeftHandComponentManager;
        
        private IEcsComponentManagerOf<NewGroupNode> _NewGroupNodeManager;
        
        public IEcsComponentManagerOf<SubMenuComponent> SubMenuComponentManager {
            get {
                return _SubMenuComponentManager;
            }
            set {
                _SubMenuComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MenuItemComponent> MenuItemComponentManager {
            get {
                return _MenuItemComponentManager;
            }
            set {
                _MenuItemComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MenuSelectionComponent> MenuSelectionComponentManager {
            get {
                return _MenuSelectionComponentManager;
            }
            set {
                _MenuSelectionComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MenuComponent> MenuComponentManager {
            get {
                return _MenuComponentManager;
            }
            set {
                _MenuComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<SubMenuItemComponent> SubMenuItemComponentManager {
            get {
                return _SubMenuItemComponentManager;
            }
            set {
                _SubMenuItemComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RightHandComponent> RightHandComponentManager {
            get {
                return _RightHandComponentManager;
            }
            set {
                _RightHandComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<LeftHandComponent> LeftHandComponentManager {
            get {
                return _LeftHandComponentManager;
            }
            set {
                _LeftHandComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<NewGroupNode> NewGroupNodeManager {
            get {
                return _NewGroupNodeManager;
            }
            set {
                _NewGroupNodeManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            SubMenuComponentManager = ComponentSystem.RegisterComponent<SubMenuComponent>(6);
            MenuItemComponentManager = ComponentSystem.RegisterComponent<MenuItemComponent>(5);
            MenuSelectionComponentManager = ComponentSystem.RegisterComponent<MenuSelectionComponent>(3);
            MenuComponentManager = ComponentSystem.RegisterComponent<MenuComponent>(4);
            SubMenuItemComponentManager = ComponentSystem.RegisterComponent<SubMenuItemComponent>(7);
            RightHandComponentManager = ComponentSystem.RegisterComponent<RightHandComponent>(2);
            LeftHandComponentManager = ComponentSystem.RegisterComponent<LeftHandComponent>(1);
            NewGroupNodeManager = ComponentSystem.RegisterGroup<NewGroupNodeGroup,NewGroupNode>();
            this.OnEvent<uFrame.Kernel.GameReadyEvent>().Subscribe(_=>{ InitSystemGameReadyFilter(_); }).DisposeWith(this);
            this.OnEvent<uFrame.Kernel.GameReadyEvent>().Subscribe(_=>{ InitSystemGameReady2Filter(_); }).DisposeWith(this);
        }
        
        protected virtual void InitSystemGameReadyHandler(uFrame.Kernel.GameReadyEvent data, SubMenuComponent group) {
            var handler = new InitSystemGameReadyHandler();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void InitSystemGameReadyFilter(uFrame.Kernel.GameReadyEvent data) {
            var SubMenuComponentItems = SubMenuComponentManager.Components;
            for (var SubMenuComponentIndex = 0
            ; SubMenuComponentIndex < SubMenuComponentItems.Count; SubMenuComponentIndex++
            ) {
                if (!SubMenuComponentItems[SubMenuComponentIndex].Enabled) {
                    continue;
                }
                this.InitSystemGameReadyHandler(data, SubMenuComponentItems[SubMenuComponentIndex]);
            }
        }
        
        protected virtual void InitSystemGameReady2Handler(uFrame.Kernel.GameReadyEvent data, MenuComponent group) {
            var handler = new InitSystemGameReady2Handler();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void InitSystemGameReady2Filter(uFrame.Kernel.GameReadyEvent data) {
            var MenuComponentItems = MenuComponentManager.Components;
            for (var MenuComponentIndex = 0
            ; MenuComponentIndex < MenuComponentItems.Count; MenuComponentIndex++
            ) {
                if (!MenuComponentItems[MenuComponentIndex].Enabled) {
                    continue;
                }
                this.InitSystemGameReady2Handler(data, MenuComponentItems[MenuComponentIndex]);
            }
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("16fa1fb1-6996-4d2f-804c-b404adf41e98")]
    public partial class InitSystem : InitSystemBase {
        
        private static InitSystem _Instance;
        
        public InitSystem() {
            Instance = this;
        }
        
        public static InitSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
