// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using abgabe;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class ModifyObjectSystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<MovableObject> _MovableObjectManager;
        
        private IEcsComponentManagerOf<SubMenuComponent> _SubMenuComponentManager;
        
        private IEcsComponentManagerOf<MenuItemComponent> _MenuItemComponentManager;
        
        private IEcsComponentManagerOf<MenuSelectionComponent> _MenuSelectionComponentManager;
        
        private IEcsComponentManagerOf<MenuComponent> _MenuComponentManager;
        
        private IEcsComponentManagerOf<SubMenuItemComponent> _SubMenuItemComponentManager;
        
        private IEcsComponentManagerOf<RightHandComponent> _RightHandComponentManager;
        
        private IEcsComponentManagerOf<LeftHandComponent> _LeftHandComponentManager;
        
        private IEcsComponentManagerOf<NewGroupNode> _NewGroupNodeManager;
        
        public IEcsComponentManagerOf<MovableObject> MovableObjectManager {
            get {
                return _MovableObjectManager;
            }
            set {
                _MovableObjectManager = value;
            }
        }
        
        public IEcsComponentManagerOf<SubMenuComponent> SubMenuComponentManager {
            get {
                return _SubMenuComponentManager;
            }
            set {
                _SubMenuComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MenuItemComponent> MenuItemComponentManager {
            get {
                return _MenuItemComponentManager;
            }
            set {
                _MenuItemComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MenuSelectionComponent> MenuSelectionComponentManager {
            get {
                return _MenuSelectionComponentManager;
            }
            set {
                _MenuSelectionComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<MenuComponent> MenuComponentManager {
            get {
                return _MenuComponentManager;
            }
            set {
                _MenuComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<SubMenuItemComponent> SubMenuItemComponentManager {
            get {
                return _SubMenuItemComponentManager;
            }
            set {
                _SubMenuItemComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RightHandComponent> RightHandComponentManager {
            get {
                return _RightHandComponentManager;
            }
            set {
                _RightHandComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<LeftHandComponent> LeftHandComponentManager {
            get {
                return _LeftHandComponentManager;
            }
            set {
                _LeftHandComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<NewGroupNode> NewGroupNodeManager {
            get {
                return _NewGroupNodeManager;
            }
            set {
                _NewGroupNodeManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            MovableObjectManager = ComponentSystem.RegisterComponent<MovableObject>(9);
            SubMenuComponentManager = ComponentSystem.RegisterComponent<SubMenuComponent>(6);
            MenuItemComponentManager = ComponentSystem.RegisterComponent<MenuItemComponent>(5);
            MenuSelectionComponentManager = ComponentSystem.RegisterComponent<MenuSelectionComponent>(3);
            MenuComponentManager = ComponentSystem.RegisterComponent<MenuComponent>(4);
            SubMenuItemComponentManager = ComponentSystem.RegisterComponent<SubMenuItemComponent>(7);
            RightHandComponentManager = ComponentSystem.RegisterComponent<RightHandComponent>(2);
            LeftHandComponentManager = ComponentSystem.RegisterComponent<LeftHandComponent>(1);
            NewGroupNodeManager = ComponentSystem.RegisterGroup<NewGroupNodeGroup,NewGroupNode>();
            this.OnEvent<abgabe.RotateObjectEvent>().Subscribe(_=>{ ModifyObjectSystemRotateObjectEventFilter(_); }).DisposeWith(this);
            this.OnEvent<uFrame.ECS.OnTriggerEnterDispatcher>().Subscribe(_=>{ ModifyObjectSystemOnTriggerEnterFilter(_); }).DisposeWith(this);
            this.OnEvent<abgabe.DeleteObjectEvent>().Subscribe(_=>{ ModifyObjectSystemDeleteObjectEventFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void ModifyObjectSystemRotateObjectEventHandler(abgabe.RotateObjectEvent data, MovableObject group) {
            var handler = new ModifyObjectSystemRotateObjectEventHandler();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void ModifyObjectSystemRotateObjectEventFilter(abgabe.RotateObjectEvent data) {
            var MovableObjectItems = MovableObjectManager.Components;
            for (var MovableObjectIndex = 0
            ; MovableObjectIndex < MovableObjectItems.Count; MovableObjectIndex++
            ) {
                if (!MovableObjectItems[MovableObjectIndex].Enabled) {
                    continue;
                }
                this.ModifyObjectSystemRotateObjectEventHandler(data, MovableObjectItems[MovableObjectIndex]);
            }
        }
        
        protected virtual void ModifyObjectSystemOnTriggerEnterHandler(uFrame.ECS.OnTriggerEnterDispatcher data, MenuSelectionComponent collider, MovableObject source) {
            var handler = new ModifyObjectSystemOnTriggerEnterHandler();
            handler.System = this;
            handler.Event = data;
            handler.Collider = collider;
            handler.Source = source;
            StartCoroutine(handler.Execute());
        }
        
        protected void ModifyObjectSystemOnTriggerEnterFilter(uFrame.ECS.OnTriggerEnterDispatcher data) {
            var ColliderMenuSelectionComponent = MenuSelectionComponentManager[data.ColliderId];
            if (ColliderMenuSelectionComponent == null) {
                return;
            }
            if (!ColliderMenuSelectionComponent.Enabled) {
                return;
            }
            var SourceMovableObject = MovableObjectManager[data.EntityId];
            if (SourceMovableObject == null) {
                return;
            }
            if (!SourceMovableObject.Enabled) {
                return;
            }
            this.ModifyObjectSystemOnTriggerEnterHandler(data, ColliderMenuSelectionComponent, SourceMovableObject);
        }
        
        protected virtual void ModifyObjectSystemDeleteObjectEventHandler(abgabe.DeleteObjectEvent data, MovableObject group) {
            var handler = new ModifyObjectSystemDeleteObjectEventHandler();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            StartCoroutine(handler.Execute());
        }
        
        protected void ModifyObjectSystemDeleteObjectEventFilter(abgabe.DeleteObjectEvent data) {
            var MovableObjectItems = MovableObjectManager.Components;
            for (var MovableObjectIndex = 0
            ; MovableObjectIndex < MovableObjectItems.Count; MovableObjectIndex++
            ) {
                if (!MovableObjectItems[MovableObjectIndex].Enabled) {
                    continue;
                }
                this.ModifyObjectSystemDeleteObjectEventHandler(data, MovableObjectItems[MovableObjectIndex]);
            }
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("d07a357a-7cd9-4d86-8cd5-bd0002b6b628")]
    public partial class ModifyObjectSystem : ModifyObjectSystemBase {
        
        private static ModifyObjectSystem _Instance;
        
        [UnityEngine.SerializeField()]
        private GameObject _selectedObject;
        
        public ModifyObjectSystem() {
            Instance = this;
        }
        
        public static ModifyObjectSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
        
        public GameObject selectedObject {
            get {
                return _selectedObject;
            }
            set {
                _selectedObject = value;
            }
        }
    }
}
