// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(4)]
    [uFrame.Attributes.uFrameIdentifier("4debeae6-ae46-4e27-8823-d90be568bc12")]
    public partial class MenuComponent : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 4;
            }
        }
    }
}
