// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(3)]
    [uFrame.Attributes.uFrameIdentifier("d1e394d5-5972-4b67-a98b-eab1348aa519")]
    public partial class MenuSelectionComponent : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 3;
            }
        }
    }
}
