// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(7)]
    [uFrame.Attributes.uFrameIdentifier("37640a6a-f520-4d70-9ca7-eb2bedf7f9a4")]
    public partial class SubMenuItemComponent : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private GameObject _instantiate;
        
        private Subject<PropertyChangedEvent<GameObject>> _instantiateObservable;
        
        private PropertyChangedEvent<GameObject> _instantiateEvent;
        
        public override int ComponentId {
            get {
                return 7;
            }
        }
        
        public IObservable<PropertyChangedEvent<GameObject>> instantiateObservable {
            get {
                return _instantiateObservable ?? (_instantiateObservable = new Subject<PropertyChangedEvent<GameObject>>());
            }
        }
        
        public GameObject instantiate {
            get {
                return _instantiate;
            }
            set {
                Setinstantiate(value);
            }
        }
        
        public virtual void Setinstantiate(GameObject value) {
            SetProperty(ref _instantiate, value, ref _instantiateEvent, _instantiateObservable);
        }
    }
}
