// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    [UnityEditor.InitializeOnLoadAttribute()]
    [uFrame.Attributes.uFrameIdentifier("303b99d4-4bbd-47c8-9800-bf73f9d10e52")]
    public class abgabeEditorExtensions {
        
        [UnityEditor.MenuItem("GameObject/Create abgabe Kernel", false, 0)]
        public static void AddKernel() {
            Invert.uFrame.ECS.Templates.EcsEditorExtensionTemplate.AddEcsKernelWith<abgabe.abgabeLoader>();
        }
    }
}
