// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace abgabe {
    using abgabe;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.EventId(2)]
    public partial class SubMenuSelectEvent : object {
        
        [UnityEngine.SerializeField()]
        private GameObject _msc;
        
        [UnityEngine.SerializeField()]
        private GameObject _instantiate;
        
        public GameObject msc {
            get {
                return _msc;
            }
            set {
                _msc = value;
            }
        }
        
        public GameObject instantiate {
            get {
                return _instantiate;
            }
            set {
                _instantiate = value;
            }
        }
    }
}
